/**
 * build-styles.mjs — emits dist/styles.css after the TypeScript build.
 *
 * Atlas components are Tailwind-class based; they don't ship compiled
 * component CSS. What `styles.css` DOES provide is the `:root` block of
 * token CSS variables (`--primary`, `--radius`, `--spacing-*`, …) so a
 * fresh app that doesn't already maintain its own `globals.css` can
 * `import "@atlas/design-system/styles.css"` and get working defaults.
 *
 * Apps that already define these variables (e.g. Xeekrsmainapp) do NOT
 * need this import — their globals.css wins.
 *
 * The token block is hard-coded here rather than imported from compiled
 * sources, so this script has no Node ESM resolution wrinkles and stays
 * easy to read alongside the rest of the brand spec.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const out = new URL("../dist/styles.css", import.meta.url);
mkdirSync(dirname(out.pathname), { recursive: true });

const css = `/* Atlas Design System — token defaults.
 * Generated by scripts/build-styles.mjs. Do not edit by hand.
 * Apps with their own globals.css token block can skip importing this. */

:root {
  /* Surfaces & text */
  --background-rgb: 249 249 244;
  --background: rgb(var(--background-rgb));
  --foreground-rgb: 18 33 32;
  --foreground: rgb(var(--foreground-rgb));
  --card-rgb: 255 255 255;
  --card: rgb(var(--card-rgb));
  --card-foreground-rgb: 68 64 60;
  --card-foreground: rgb(var(--card-foreground-rgb));
  --popover-rgb: 252 252 247;
  --popover: rgb(var(--popover-rgb));
  --popover-foreground-rgb: 68 64 60;
  --popover-foreground: rgb(var(--popover-foreground-rgb));

  /* Brand & emphasis */
  --primary-rgb: 12 33 32;
  --primary: rgb(var(--primary-rgb));
  --primary-foreground-rgb: 255 255 255;
  --primary-foreground: rgb(var(--primary-foreground-rgb));
  --secondary-rgb: 255 255 255;
  --secondary: rgb(var(--secondary-rgb));
  --secondary-foreground-rgb: 12 33 32;
  --secondary-foreground: rgb(var(--secondary-foreground-rgb));
  --muted-rgb: 237 237 232;
  --muted: rgb(var(--muted-rgb));
  --muted-foreground-rgb: 120 113 108;
  --muted-foreground: rgb(var(--muted-foreground-rgb));
  --accent-rgb: 76 111 220;
  --accent: rgb(var(--accent-rgb));
  --accent-foreground-rgb: 255 255 255;
  --accent-foreground: rgb(var(--accent-foreground-rgb));
  --destructive-rgb: 243 18 96;
  --destructive: rgb(var(--destructive-rgb));
  --destructive-foreground-rgb: 255 255 255;
  --destructive-foreground: rgb(var(--destructive-foreground-rgb));

  /* Semantic status */
  --success-rgb: 16 185 129;
  --success: rgb(var(--success-rgb));
  --success-foreground-rgb: 255 255 255;
  --success-foreground: rgb(var(--success-foreground-rgb));
  --success-light: rgb(16 185 129 / 0.1);
  --error-rgb: 239 68 68;
  --error: rgb(var(--error-rgb));
  --error-foreground-rgb: 255 255 255;
  --error-foreground: rgb(var(--error-foreground-rgb));
  --error-light: rgb(239 68 68 / 0.1);
  --warning-rgb: 245 158 11;
  --warning: rgb(var(--warning-rgb));
  --warning-foreground-rgb: 255 255 255;
  --warning-foreground: rgb(var(--warning-foreground-rgb));
  --warning-light: rgb(245 158 11 / 0.1);
  --info-rgb: 59 130 246;
  --info: rgb(var(--info-rgb));
  --info-foreground-rgb: 255 255 255;
  --info-foreground: rgb(var(--info-foreground-rgb));
  --info-light: rgb(59 130 246 / 0.1);

  /* Borders, inputs, focus */
  --border-rgb: 237 237 232;
  --border: rgb(var(--border-rgb));
  --input-rgb: 255 255 255;
  --input: rgb(var(--input-rgb));
  --input-background-rgb: 255 255 255;
  --input-background: rgb(var(--input-background-rgb));
  --ring-rgb: 153 199 251;
  --ring: rgb(var(--ring-rgb));

  /* Layout */
  --radius: 12px;
  --spacing-1: 4px;
  --spacing-2: 8px;
  --spacing-3: 12px;
  --spacing-4: 16px;
  --spacing-5: 20px;
  --spacing-6: 24px;
  --spacing-8: 32px;
  --spacing-10: 40px;
  --spacing-12: 48px;
  --spacing-16: 64px;
  --spacing-20: 80px;
  --spacing-24: 96px;

  /* Typography */
  --font-family-heading: "Raleway", sans-serif;
  --font-family-body: "Open Sans", sans-serif;
  --font-family-base: "Open Sans", sans-serif;
  --text-xs: 12px;
  --text-sm: 14px;
  --text-base: 16px;
  --text-lg: 18px;
  --text-xl: 20px;
  --text-2xl: 24px;
  --text-3xl: 30px;
  --text-4xl: 36px;
  --font-weight-normal: 400;
  --font-weight-medium: 500;
  --font-weight-semibold: 600;
  --font-weight-bold: 700;
}
`;

writeFileSync(out, css);
console.log("build-styles: wrote dist/styles.css");
