/**
 * AiGeneratedBadge — small pill marking AI-authored content.
 *
 * Inspired by Xeekrs's posting flow patterns (job-posting/JobPosting*.tsx).
 * The badge is a leading-icon pill with a lavender / sparkle aesthetic
 * — visually distinct from semantic status badges (success / warning).
 *
 * Use cases: "Generated by AI" caption under suggested copy, "AI Draft"
 * label on a wizard step, inline annotation on hover-cards.
 */

import { forwardRef, type ReactNode } from "react";
import { Sparkles } from "lucide-react";
import { cnHero } from "../../../shared/cn-hero";

export type AiGeneratedBadgeTone = "subtle" | "solid";

export interface AiGeneratedBadgeProps {
  /** Defaults to "AI generated". */
  children?: ReactNode;
  tone?: AiGeneratedBadgeTone;
  /** Hide the leading sparkle icon. */
  hideIcon?: boolean;
  className?: string;
  testId?: string;
  id?: string;
}

const SUBTLE =
  "border border-lavender-300/60 bg-lavender-50 text-lavender-800";
const SOLID =
  "border border-transparent bg-lavender-500 text-earth-900";

export const AiGeneratedBadge = forwardRef<HTMLSpanElement, AiGeneratedBadgeProps>(
  function AiGeneratedBadge(
    { children = "AI generated", tone = "subtle", hideIcon = false, className, testId, id },
    ref,
  ) {
    return (
      <span
        ref={ref}
        id={id}
        data-testid={testId}
        className={cnHero(
          "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold tracking-wide",
          tone === "solid" ? SOLID : SUBTLE,
          className,
        )}
      >
        {hideIcon ? null : <Sparkles className="size-3 shrink-0" aria-hidden />}
        {children}
      </span>
    );
  },
);

AiGeneratedBadge.displayName = "AiGeneratedBadge";
